%------------------------
% THEME COLORS
%------------------------

% Couleur de fond de cadre
\definecolor{uBackColor}{RGB}{220,220,220}


\definecolor{uAlertColor}{rgb}{0.36, 0.54, 0.66}

% Couleur des titres et des fonds
% Orange : {255,121,0}
% Cnam : {160,0,0} 

\definecolor{BaseColor}{RGB}{255,121,0}

\colorlet{uMainColor}{BaseColor}


\definecolor{CoverColor}{RGB}{255,121,0}

\colorlet{uCoverColor}{CoverColor}

\definecolor{uTextColor}{RGB}{255,255,255}
