%------------------------
% THEME COLORS
%------------------------

% Couleur de fond de cadre
\definecolor{uBackColor}{RGB}{220,220,220}
\definecolor{uAlertColor}{rgb}{0.36, 0.54, 0.66}
% Couleur des titres et des fonds
\definecolor{OrangeColor}{RGB}{255,121,0}
\definecolor{CnamColor}{RGB}{160,0,0} 
\definecolor{Cyberskills4allBlue}{RGB}{33,39,81}
\definecolor{Cyberskills4allCyan}{RGB}{64,144,203}
\definecolor{Cyberskills4allPink}{RGB}{230,32,116}

\definecolor{MyBlack}{RGB}{100,100,100}

\colorlet{uMainColorUrl}{Cyberskills4allPink}

\colorlet{BaseColor}{Cyberskills4allCyan}
\colorlet{uMainColor}{BaseColor}


%\colorlet{CoverColor}{Cyberskills4allBlue}

\colorlet{CoverColor}{MyBlack}

\colorlet{uCoverColor}{CoverColor}

\definecolor{uTextColor}{RGB}{33,33,33}
